---
ID: "95d5e1ef-cacc-4dc2-a570-1dc8a7af956d"
Parent: "07d656e2-10a7-4400-9c06-3801c051237c"
Template: "07d656e2-10a7-4400-9c06-3801c051237c"
Path: "/sitecore/templates/Project/simons-sai-playground/Footer/Footer/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260923T112113Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\simon.hauck@merkle.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\simon.hauck@merkle.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "7e693e06-fbac-4e78-9198-d0513b84b1d1"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\simon.hauck@merkle.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260923T112113Z
