---
ID: "880f6f37-8bd6-4145-bc81-788d8280f840"
Parent: "58bbbf94-d79c-4980-93d3-dd9d5137026c"
Template: "58bbbf94-d79c-4980-93d3-dd9d5137026c"
Path: "/sitecore/templates/Project/simons-sai-playground/Product Card Grid/Product Card Grid Folder/__Standard Values"
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {3C7B73FE-5550-4496-BCED-D86B17D606AA}
    {58BBBF94-D79C-4980-93D3-DD9D5137026C}
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "27feb15f-8a7c-4ab6-9b9e-347ca36da528"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260922T235232Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\simon.hauck@merkle.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\simon.hauck@merkle.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "e5e724d5-aafa-4527-a77e-2631b7dd5fda"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\simon.hauck@merkle.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260922T235232Z
